spring:
  application:
    name: audit-log-service

  # データベース設定
  datasource:
    url: jdbc:h2:mem:auditdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  # JPA設定
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # セカンドレベルキャッシュの設定
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax.cache:
          provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
        generate_statistics: true # キャッシュ統計の有効化

# アプリケーション固有の設定
audit:
  # アーカイブ設定
  archive:
    base-dir: archives
    retention:
      daily: 30  # 日次アーカイブの保持期間（日）
      monthly: 12 # 月次アーカイブの保持期間（月）

  # キャッシュ設定
  cache:
    caffeine:
      audit-log:
        maximum-size: 1000
        expire-after-write: 15m
        record-stats: true
    hibernate:
      entity:
        # エンティティキャッシュの設定
        audit-log:
          maximum-size: 1000
          expire-after-write: 30m
      query:
        # クエリキャッシュの設定
        audit.log.byEventType:
          maximum-size: 100
          expire-after-write: 15m
        audit.log.byUserId:
          maximum-size: 100
          expire-after-write: 15m
        audit.log.byDateRange:
          maximum-size: 100
          expire-after-write: 15m
        audit.log.bySeverityAndDate:
          maximum-size: 100
          expire-after-write: 15m
        audit.log.byDateRangePaged:
          maximum-size: 100
          expire-after-write: 15m
        audit.log.search:
          maximum-size: 100
          expire-after-write: 15m
        audit.log.count:
          maximum-size: 50
          expire-after-write: 15m

# アクチュエータ設定
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

# ログ設定
logging:
  level:
    root: INFO
    com.example.javase17learningproject: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
      cache: DEBUG